# Generated by Django 4.2.2 on 2025-05-31 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=100, verbose_name='نام فروشگاه')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='seller_logos/', verbose_name='لوگو')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='seller_banners/', verbose_name='بنر')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('suspended', 'تعلیق شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('identification_type', models.CharField(choices=[('national_id', 'کارت ملی'), ('business_license', 'مجوز کسب و کار'), ('both', 'هر دو')], default='national_id', max_length=20, verbose_name='نوع احراز هویت')),
                ('identification_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره شناسایی')),
                ('identification_image', models.ImageField(blank=True, null=True, upload_to='seller_identification/', verbose_name='تصویر مدرک')),
                ('business_license', models.ImageField(blank=True, null=True, upload_to='seller_licenses/', verbose_name='تصویر مجوز کسب')),
                ('bank_account_number', models.CharField(blank=True, max_length=26, null=True, verbose_name='شماره حساب بانکی')),
                ('bank_sheba', models.CharField(blank=True, max_length=26, null=True, verbose_name='شماره شبا')),
                ('bank_card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت بانکی')),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام بانک')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن ثابت')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='اینستاگرام')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='تلگرام')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='امتیاز')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نظرات')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فروش')),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='درآمد کل')),
                ('commission_type', models.CharField(choices=[('fixed', 'ثابت'), ('percentage', 'درصدی'), ('tiered', 'پلکانی')], default='percentage', max_length=20, verbose_name='نوع کمیسیون')),
                ('commission_value', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='مقدار کمیسیون')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='موجودی حساب')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فروشنده',
                'verbose_name_plural': 'فروشندگان',
            },
        ),
        migrations.CreateModel(
            name='TieredCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_sales', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='حداقل فروش')),
                ('max_sales', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='حداکثر فروش')),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد کمیسیون')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiered_commissions', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'کمیسیون پلکانی',
                'verbose_name_plural': 'کمیسیون\u200cهای پلکانی',
                'ordering': ['min_sales'],
            },
        ),
        migrations.CreateModel(
            name='SellerWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('paid', 'پرداخت شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه تراکنش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت مدیر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'برداشت فروشنده',
                'verbose_name_plural': 'برداشت\u200cهای فروشنده',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='امتیاز')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='sellers.seller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نظر فروشنده',
                'verbose_name_plural': 'نظرات فروشنده',
                'unique_together': {('seller', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SellerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='categories.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی فروشنده',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای فروشنده',
                'unique_together': {('seller', 'category')},
            },
        ),
    ]
