# Generated by Django 4.2.2 on 2025-06-01 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(verbose_name='شناسه محتوا')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='تعداد لایک\u200cها')),
                ('dislikes_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دیسلایک\u200cها')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت مدیر')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع محتوا')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment', verbose_name='نظر والد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('like', 'لایک'), ('dislike', 'دیسلایک')], max_length=10, verbose_name='نوع رای')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='comments.comment', verbose_name='نظر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رای نظر',
                'verbose_name_plural': 'آرای نظرات',
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('spam', 'اسپم'), ('offensive', 'توهین\u200cآمیز'), ('irrelevant', 'غیرمرتبط'), ('advertising', 'تبلیغاتی'), ('other', 'سایر')], max_length=20, verbose_name='دلیل گزارش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('resolved', 'بررسی شده'), ('dismissed', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت مدیر')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='comments.comment', verbose_name='نظر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200cدهنده')),
            ],
            options={
                'verbose_name': 'گزارش نظر',
                'verbose_name_plural': 'گزارش\u200cهای نظرات',
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'object_id'], name='comments_co_content_cff8bd_idx'),
        ),
    ]
