# Generated by Django 4.2.2 on 2025-05-31 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('percentage', 'درصدی')], max_length=20, verbose_name='نوع تخفیف')),
                ('value', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مقدار تخفیف')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='حداکثر تخفیف')),
                ('min_purchase', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حداقل خرید')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='محدودیت استفاده')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_first_purchase_only', models.BooleanField(default=False, verbose_name='فقط اولین خرید')),
                ('is_one_time_per_user', models.BooleanField(default=False, verbose_name='یک بار برای هر کاربر')),
                ('is_for_specific_users', models.BooleanField(default=False, verbose_name='فقط برای کاربران خاص')),
                ('is_for_specific_products', models.BooleanField(default=False, verbose_name='فقط برای محصولات خاص')),
                ('specific_categories', models.ManyToManyField(blank=True, related_name='specific_discounts', to='categories.category', verbose_name='دسته\u200cبندی\u200cهای خاص')),
                ('specific_products', models.ManyToManyField(blank=True, related_name='specific_discounts', to='products.product', verbose_name='محصولات خاص')),
                ('specific_users', models.ManyToManyField(blank=True, related_name='specific_discounts', to=settings.AUTH_USER_MODEL, verbose_name='کاربران خاص')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نام جایزه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('points_required', models.PositiveIntegerField(verbose_name='امتیاز مورد نیاز')),
                ('reward_type', models.CharField(choices=[('discount', 'کد تخفیف'), ('product', 'محصول رایگان'), ('shipping', 'ارسال رایگان')], max_length=20, verbose_name='نوع جایزه')),
                ('discount_value', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='مقدار تخفیف')),
                ('discount_type', models.CharField(blank=True, choices=[('fixed', 'مبلغ ثابت'), ('percentage', 'درصدی')], max_length=20, null=True, verbose_name='نوع تخفیف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_rewards', to='products.product')),
            ],
            options={
                'verbose_name': 'جایزه وفاداری',
                'verbose_name_plural': 'جوایز وفاداری',
                'ordering': ['points_required'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyRewardClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claimed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('delivered', 'تحویل داده شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('discount_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد تخفیف')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_reward_claims', to='orders.order')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='discounts.loyaltyreward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_reward_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست جایزه وفاداری',
                'verbose_name_plural': 'درخواست\u200cهای جایزه وفاداری',
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.PositiveIntegerField(verbose_name='امتیاز')),
                ('reason', models.CharField(max_length=100, verbose_name='دلیل')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه مرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'امتیاز وفاداری',
                'verbose_name_plural': 'امتیازهای وفاداری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ استفاده')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مقدار تخفیف')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='discounts.discount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'استفاده از تخفیف',
                'verbose_name_plural': 'استفاده\u200cهای تخفیف',
                'ordering': ['-used_at'],
                'unique_together': {('discount', 'order')},
            },
        ),
    ]
