# Generated by Django 4.2.2 on 2025-05-31 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نام روش ارسال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('cost', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='هزینه ارسال')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('estimated_delivery_days', models.PositiveIntegerField(default=3, verbose_name='تخمین روزهای تحویل')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='shipping_icons/', verbose_name='آیکون')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'روش ارسال',
                'verbose_name_plural': 'روش\u200cهای ارسال',
                'ordering': ['cost'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نام منطقه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'منطقه ارسال',
                'verbose_name_plural': 'مناطق ارسال',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نام انبار')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبارها',
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_transit', 'در حال انتقال'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_transfers', to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='shipping.warehouse')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='shipping.warehouse')),
            ],
            options={
                'verbose_name': 'انتقال بین انبار',
                'verbose_name_plural': 'انتقالات بین انبار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping.warehousetransfer')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
            ],
            options={
                'verbose_name': 'آیتم انتقال بین انبار',
                'verbose_name_plural': 'آیتم\u200cهای انتقال بین انبار',
            },
        ),
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock', models.PositiveIntegerField(verbose_name='موجودی')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='موقعیت در انبار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='products.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shipping.warehouse')),
            ],
            options={
                'verbose_name': 'موجودی محصول در انبار',
                'verbose_name_plural': 'موجودی محصولات در انبار',
                'unique_together': {('warehouse', 'product', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='هزینه ارسال')),
                ('estimated_delivery_days', models.PositiveIntegerField(default=3, verbose_name='تخمین روزهای تحویل')),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingmethod')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingzone')),
            ],
            options={
                'verbose_name': 'نرخ ارسال',
                'verbose_name_plural': 'نرخ\u200cهای ارسال',
                'unique_together': {('shipping_method', 'zone')},
            },
        ),
        migrations.CreateModel(
            name='ShippingLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='shipping.shippingzone')),
            ],
            options={
                'verbose_name': 'موقعیت ارسال',
                'verbose_name_plural': 'موقعیت\u200cهای ارسال',
                'unique_together': {('zone', 'province', 'city')},
            },
        ),
    ]
