# Generated by Django 4.2.2 on 2025-05-31 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('login', 'ورود'), ('logout', 'خروج'), ('register', 'ثبت نام'), ('password_change', 'تغییر رمز عبور'), ('profile_update', 'به\u200cروزرسانی پروفایل'), ('order_create', 'ایجاد سفارش'), ('order_payment', 'پرداخت سفارش'), ('review_submit', 'ثبت نظر'), ('wishlist_add', 'افزودن به علاقه\u200cمندی\u200cها'), ('wishlist_remove', 'حذف از علاقه\u200cمندی\u200cها')], max_length=20, verbose_name='نوع فعالیت')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='مرورگر کاربر')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه شیء')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ فعالیت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فعالیت کاربر',
                'verbose_name_plural': 'فعالیت\u200cهای کاربر',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=255, verbose_name='عبارت جستجو')),
                ('session_id', models.CharField(max_length=100, verbose_name='شناسه نشست')),
                ('results_count', models.IntegerField(default=0, verbose_name='تعداد نتایج')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ جستجو')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to='categories.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جستجو',
                'verbose_name_plural': 'جستجوها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('total_sales', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مجموع فروش')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='تعداد سفارش\u200cها')),
                ('average_order_value', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='میانگین ارزش سفارش')),
                ('total_discount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مجموع تخفیف')),
                ('total_shipping', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مجموع هزینه ارسال')),
                ('total_tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مجموع مالیات')),
                ('total_refund', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مجموع برگشتی')),
                ('net_sales', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='فروش خالص')),
            ],
            options={
                'verbose_name': 'گزارش فروش',
                'verbose_name_plural': 'گزارش\u200cهای فروش',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, verbose_name='شناسه نشست')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('referrer', models.URLField(blank=True, null=True, verbose_name='ارجاع\u200cدهنده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بازدید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بازدید محصول',
                'verbose_name_plural': 'بازدیدهای محصول',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, verbose_name='شناسه نشست')),
                ('url', models.URLField(verbose_name='آدرس صفحه')),
                ('page_title', models.CharField(blank=True, max_length=255, verbose_name='عنوان صفحه')),
                ('referrer', models.URLField(blank=True, null=True, verbose_name='ارجاع\u200cدهنده')),
                ('user_agent', models.TextField(blank=True, verbose_name='مرورگر کاربر')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='نوع دستگاه')),
                ('os', models.CharField(blank=True, max_length=50, verbose_name='سیستم عامل')),
                ('browser', models.CharField(blank=True, max_length=50, verbose_name='مرورگر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بازدید')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بازدید صفحه',
                'verbose_name_plural': 'بازدیدهای صفحه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, verbose_name='شناسه نشست')),
                ('event_type', models.CharField(choices=[('create', 'ایجاد سبد'), ('add', 'افزودن محصول'), ('remove', 'حذف محصول'), ('update', 'به\u200cروزرسانی تعداد'), ('clear', 'خالی کردن سبد'), ('checkout', 'تکمیل خرید'), ('abandon', 'رها کردن سبد')], max_length=20, verbose_name='نوع رویداد')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ رویداد')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.cart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_events', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رویداد سبد خرید',
                'verbose_name_plural': 'رویدادهای سبد خرید',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدیدها')),
                ('add_to_carts', models.PositiveIntegerField(default=0, verbose_name='افزودن به سبد')),
                ('purchases', models.PositiveIntegerField(default=0, verbose_name='خریدها')),
                ('revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='درآمد')),
                ('conversion_rate', models.FloatField(default=0, verbose_name='نرخ تبدیل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='products.product')),
            ],
            options={
                'verbose_name': 'عملکرد محصول',
                'verbose_name_plural': 'عملکرد محصولات',
                'ordering': ['-date'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
