# Generated by Django 4.2.2 on 2025-05-31 15:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('sellers', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ستاره'), (2, '2 ستاره'), (3, '3 ستاره'), (4, '4 ستاره'), (5, '5 ستاره')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان نظر')),
                ('comment', models.TextField(verbose_name='متن نظر')),
                ('quality_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 ستاره'), (2, '2 ستاره'), (3, '3 ستاره'), (4, '4 ستاره'), (5, '5 ستاره')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز کیفیت')),
                ('value_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 ستاره'), (2, '2 ستاره'), (3, '3 ستاره'), (4, '4 ستاره'), (5, '5 ستاره')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز ارزش خرید')),
                ('delivery_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 ستاره'), (2, '2 ستاره'), (3, '3 ستاره'), (4, '4 ستاره'), (5, '5 ستاره')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز ارسال')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت مدیر')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='تعداد مفید بودن')),
                ('not_helpful_count', models.PositiveIntegerField(default=0, verbose_name='تعداد مفید نبودن')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='خرید تایید شده')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderitem', verbose_name='آیتم سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_detailed_reviews', to='products.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ReviewSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='تعداد کل نظرات')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='میانگین امتیاز')),
                ('rating_1_count', models.PositiveIntegerField(default=0, verbose_name='تعداد 1 ستاره')),
                ('rating_2_count', models.PositiveIntegerField(default=0, verbose_name='تعداد 2 ستاره')),
                ('rating_3_count', models.PositiveIntegerField(default=0, verbose_name='تعداد 3 ستاره')),
                ('rating_4_count', models.PositiveIntegerField(default=0, verbose_name='تعداد 4 ستاره')),
                ('rating_5_count', models.PositiveIntegerField(default=0, verbose_name='تعداد 5 ستاره')),
                ('average_quality_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='میانگین امتیاز کیفیت')),
                ('average_value_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='میانگین امتیاز ارزش')),
                ('average_delivery_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='میانگین امتیاز ارسال')),
                ('verified_purchases_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد خریدهای تایید شده')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_summary', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'خلاصه نظرات',
                'verbose_name_plural': 'خلاصه نظرات',
            },
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='پیام پاسخ')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='reviews.review', verbose_name='نظر')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.seller', verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'پاسخ به نظر',
                'verbose_name_plural': 'پاسخ\u200cهای نظرات',
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='reviews/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='توضیح تصویر')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review', verbose_name='نظر')),
            ],
            options={
                'verbose_name': 'تصویر نظر',
                'verbose_name_plural': 'تصاویر نظرات',
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('spam', 'اسپم'), ('inappropriate', 'نامناسب'), ('fake', 'جعلی'), ('offensive', 'توهین\u200cآمیز'), ('irrelevant', 'غیرمرتبط'), ('other', 'سایر')], max_length=20, verbose_name='دلیل گزارش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('reviewed', 'بررسی شده'), ('resolved', 'حل شده'), ('dismissed', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت مدیر')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review', verbose_name='نظر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200cدهنده')),
            ],
            options={
                'verbose_name': 'گزارش نظر',
                'verbose_name_plural': 'گزارش\u200cهای نظرات',
                'unique_together': {('user', 'review')},
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_helpful', models.BooleanField(verbose_name='مفید است')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='reviews.review', verbose_name='نظر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رای مفید بودن نظر',
                'verbose_name_plural': 'آرای مفید بودن نظرات',
                'unique_together': {('user', 'review')},
            },
        ),
    ]
