# Generated by Django 4.2.2 on 2025-06-01 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_order', models.BooleanField(default=True, verbose_name='اعلان سفارش از طریق ایمیل')),
                ('email_payment', models.BooleanField(default=True, verbose_name='اعلان پرداخت از طریق ایمیل')),
                ('email_product', models.BooleanField(default=True, verbose_name='اعلان محصول از طریق ایمیل')),
                ('email_comment', models.BooleanField(default=True, verbose_name='اعلان نظر از طریق ایمیل')),
                ('email_review', models.BooleanField(default=True, verbose_name='اعلان بررسی از طریق ایمیل')),
                ('email_account', models.BooleanField(default=True, verbose_name='اعلان حساب کاربری از طریق ایمیل')),
                ('email_system', models.BooleanField(default=True, verbose_name='اعلان سیستمی از طریق ایمیل')),
                ('email_promotion', models.BooleanField(default=False, verbose_name='اعلان تبلیغاتی از طریق ایمیل')),
                ('sms_order', models.BooleanField(default=True, verbose_name='اعلان سفارش از طریق پیامک')),
                ('sms_payment', models.BooleanField(default=True, verbose_name='اعلان پرداخت از طریق پیامک')),
                ('sms_product', models.BooleanField(default=False, verbose_name='اعلان محصول از طریق پیامک')),
                ('sms_comment', models.BooleanField(default=False, verbose_name='اعلان نظر از طریق پیامک')),
                ('sms_review', models.BooleanField(default=False, verbose_name='اعلان بررسی از طریق پیامک')),
                ('sms_account', models.BooleanField(default=True, verbose_name='اعلان حساب کاربری از طریق پیامک')),
                ('sms_system', models.BooleanField(default=True, verbose_name='اعلان سیستمی از طریق پیامک')),
                ('sms_promotion', models.BooleanField(default=False, verbose_name='اعلان تبلیغاتی از طریق پیامک')),
                ('push_order', models.BooleanField(default=True, verbose_name='اعلان سفارش از طریق نوتیفیکیشن')),
                ('push_payment', models.BooleanField(default=True, verbose_name='اعلان پرداخت از طریق نوتیفیکیشن')),
                ('push_product', models.BooleanField(default=True, verbose_name='اعلان محصول از طریق نوتیفیکیشن')),
                ('push_comment', models.BooleanField(default=True, verbose_name='اعلان نظر از طریق نوتیفیکیشن')),
                ('push_review', models.BooleanField(default=True, verbose_name='اعلان بررسی از طریق نوتیفیکیشن')),
                ('push_account', models.BooleanField(default=True, verbose_name='اعلان حساب کاربری از طریق نوتیفیکیشن')),
                ('push_system', models.BooleanField(default=True, verbose_name='اعلان سیستمی از طریق نوتیفیکیشن')),
                ('push_promotion', models.BooleanField(default=False, verbose_name='اعلان تبلیغاتی از طریق نوتیفیکیشن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تنظیمات اعلان',
                'verbose_name_plural': 'تنظیمات اعلان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('order', 'سفارش'), ('payment', 'پرداخت'), ('product', 'محصول'), ('comment', 'نظر'), ('review', 'بررسی'), ('account', 'حساب کاربری'), ('system', 'سیستمی'), ('promotion', 'تبلیغاتی')], max_length=20, verbose_name='نوع')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], default='medium', max_length=10, verbose_name='اولویت')),
                ('object_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه محتوا')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای اضافی')),
                ('action_url', models.CharField(blank=True, max_length=255, verbose_name='لینک عمل')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='نوع محتوا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='توکن دستگاه')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=10, verbose_name='پلتفرم')),
                ('device_name', models.CharField(blank=True, max_length=255, verbose_name='نام دستگاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='آخرین استفاده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'توکن دستگاه',
                'verbose_name_plural': 'توکن\u200cهای دستگاه',
                'unique_together': {('user', 'token')},
            },
        ),
    ]
